shallow_clone: true

version: 0.00-{build}

image:
  - Ubuntu1804

install:
  - sudo apt-get install -qq mingw-w64 mingw-w64-tools mingw-w64-common gcc-mingw-w64 g++-mingw-w64 binutils-mingw-w64 meson
  
build_script:
  - sudo chmod +x package-release.sh
  - ./package-release.sh ${APPVEYOR_REPO_BRANCH}.${APPVEYOR_BUILD_VERSION} build
  
artifacts:
  - path: build
    name: dxup
